### ISSUE TITLE
Will werkkzeug be released under MIT?

### ISSUE THREAD

**Issue by cookiengineer** [farbrausch/fr_public#88]
As the title states, werkkzeug is currently open sourced under a third-party license. For many other open source engine projects that might want to use a fork of werkkzeug (with given notice of original authors) it's still not possible to distribute it due to the license.

If it would be released under MIT, we were able to publicly fork it on github and make an awesome project out of it that still could be a game changer (even if it's a couple years old now).

**Comment by cookiengineer** [comment]
@kebby Is this repository still maintained or inactive and just a dump for old projects? still no reply in almost 3 years 😞

**Comment by cookiengineer** [comment]
Closing this issue because this repo is unmaintained.

**Comment by usernameak** [comment]
@cookiengineer that's BSD-2-Clause license.
